
version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
  app:
    build: .
    depends_on:
      - mongodb
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    environment:
      NODE_ENV: development
      MONGODB_URL: mongodb://user:mongodb@mongodb:27017/db-todolist?authSource=admin

volumes:
  mongodb:
